name: .NET # Namnet på min workflow

on: # Namnet på GitHub-händelsen som aktiverar/trigger min workflow
  push:
    


jobs: # Anger vad som ska göras 
  build: # Bygger en solution 

    runs-on: ubuntu-latest # Anger i vilken miljö en solution ska byggas 

    steps: # Beskriving av steg som skall utföras 
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/SpacePark.sln
    - name: Build
      run: dotnet build --no-restore Source/SpacePark.sln
    - name: Test Source/SpacePark.sln
      run: dotnet test --no-build --verbosity normal Source/SpacePark.sln
